#!/usr/bin/env python
#coding:utf-8

# 基于python 2.7，selenium 3.11.0，xlrd 1.1.0，xlutils 2.0.0，xlwt 1.3.0
import binascii
from selenium.common import exceptions
from selenium import webdriver
import xlrd
import xlwt
from xlutils.copy import copy
import sys
reload(sys)
sys.setdefaultencoding('utf8')

def FileOpen(FileOP):
	try:
		File = open(FileOP, "r+") # 读取文件名
		FileN = File.read()
		FileN = FileN.decode('utf-8-sig').encode('gb18030') # 解决BOM_UTF8的\xef\xbb\xbf问题
	except IOError as e:
		if FileOP == "FileText.txt":
			print u"PLEACE READ README"
		else:
			print u"PLEACE READ README"
	except UnicodeDecodeError as e:
		pass
	finally:
		print FileN
		return FileN
		File.close()
